#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ctrd_diff.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ctrd_diff.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63trd_diff.proto\x12\x1b\x63ontainerd.services.diff.v1\"\xc1\x01\n\nDescriptor\x12\x12\n\nmedia_type\x18\x01 \x01(\t\x12\x0e\n\x06\x64igest\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x03\x12M\n\x0b\x61nnotations\x18\x05 \x03(\x0b\x32\x38.containerd.services.diff.v1.Descriptor.AnnotationsEntry\x1a\x32\n\x10\x41nnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"F\n\x05Mount\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x0f\n\x07options\x18\x04 \x03(\t\"\x88\x02\n\x0b\x44iffRequest\x12\x30\n\x04left\x18\x01 \x03(\x0b\x32\".containerd.services.diff.v1.Mount\x12\x31\n\x05right\x18\x02 \x03(\x0b\x32\".containerd.services.diff.v1.Mount\x12\x12\n\nmedia_type\x18\x03 \x01(\t\x12\x0b\n\x03ref\x18\x04 \x01(\t\x12\x44\n\x06labels\x18\x05 \x03(\x0b\x32\x34.containerd.services.diff.v1.DiffRequest.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"E\n\x0c\x44iffResponse\x12\x35\n\x04\x64iff\x18\x03 \x01(\x0b\x32\'.containerd.services.diff.v1.Descriptor2c\n\x04\x44iff\x12[\n\x04\x44iff\x12(.containerd.services.diff.v1.DiffRequest\x1a).containerd.services.diff.v1.DiffResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ctrd_diff_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DESCRIPTOR_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_DESCRIPTOR_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_DIFFREQUEST_LABELSENTRY']._loaded_options = None
  _globals['_DIFFREQUEST_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_DESCRIPTOR']._serialized_start=49
  _globals['_DESCRIPTOR']._serialized_end=242
  _globals['_DESCRIPTOR_ANNOTATIONSENTRY']._serialized_start=192
  _globals['_DESCRIPTOR_ANNOTATIONSENTRY']._serialized_end=242
  _globals['_MOUNT']._serialized_start=244
  _globals['_MOUNT']._serialized_end=314
  _globals['_DIFFREQUEST']._serialized_start=317
  _globals['_DIFFREQUEST']._serialized_end=581
  _globals['_DIFFREQUEST_LABELSENTRY']._serialized_start=536
  _globals['_DIFFREQUEST_LABELSENTRY']._serialized_end=581
  _globals['_DIFFRESPONSE']._serialized_start=583
  _globals['_DIFFRESPONSE']._serialized_end=652
  _globals['_DIFF']._serialized_start=654
  _globals['_DIFF']._serialized_end=753
# @@protoc_insertion_point(module_scope)
