#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ctrd_content.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ctrd_content.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63trd_content.proto\x12\x1e\x63ontainerd.services.content.v1\"$\n\x04Info\x12\x0e\n\x06\x64igest\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\"\x1d\n\x0bInfoRequest\x12\x0e\n\x06\x64igest\x18\x01 \x01(\t\"B\n\x0cInfoResponse\x12\x32\n\x04info\x18\x01 \x01(\x0b\x32$.containerd.services.content.v1.Info\"B\n\x12ReadContentRequest\x12\x0e\n\x06\x64igest\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x0c\n\x04size\x18\x03 \x01(\x03\"3\n\x13ReadContentResponse\x12\x0e\n\x06offset\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x9e\x02\n\x13WriteContentRequest\x12;\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32+.containerd.services.content.v1.WriteAction\x12\x0b\n\x03ref\x18\x02 \x01(\t\x12\r\n\x05total\x18\x03 \x01(\x03\x12\x10\n\x08\x65xpected\x18\x04 \x01(\t\x12\x0e\n\x06offset\x18\x05 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x12O\n\x06labels\x18\x07 \x03(\x0b\x32?.containerd.services.content.v1.WriteContentRequest.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8f\x01\n\x14WriteContentResponse\x12;\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32+.containerd.services.content.v1.WriteAction\x12\x0b\n\x03ref\x18\x03 \x01(\t\x12\x0e\n\x06offset\x18\x04 \x01(\x03\x12\r\n\x05total\x18\x05 \x01(\x03\x12\x0e\n\x06\x64igest\x18\x06 \x01(\t*.\n\x0bWriteAction\x12\x08\n\x04STAT\x10\x00\x12\t\n\x05WRITE\x10\x01\x12\n\n\x06\x43OMMIT\x10\x02\x32\xd7\x02\n\x07\x43ontent\x12\x61\n\x04Info\x12+.containerd.services.content.v1.InfoRequest\x1a,.containerd.services.content.v1.InfoResponse\x12q\n\x04Read\x12\x32.containerd.services.content.v1.ReadContentRequest\x1a\x33.containerd.services.content.v1.ReadContentResponse0\x01\x12v\n\x05Write\x12\x33.containerd.services.content.v1.WriteContentRequest\x1a\x34.containerd.services.content.v1.WriteContentResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ctrd_content_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITECONTENTREQUEST_LABELSENTRY']._loaded_options = None
  _globals['_WRITECONTENTREQUEST_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_WRITEACTION']._serialized_start=747
  _globals['_WRITEACTION']._serialized_end=793
  _globals['_INFO']._serialized_start=54
  _globals['_INFO']._serialized_end=90
  _globals['_INFOREQUEST']._serialized_start=92
  _globals['_INFOREQUEST']._serialized_end=121
  _globals['_INFORESPONSE']._serialized_start=123
  _globals['_INFORESPONSE']._serialized_end=189
  _globals['_READCONTENTREQUEST']._serialized_start=191
  _globals['_READCONTENTREQUEST']._serialized_end=257
  _globals['_READCONTENTRESPONSE']._serialized_start=259
  _globals['_READCONTENTRESPONSE']._serialized_end=310
  _globals['_WRITECONTENTREQUEST']._serialized_start=313
  _globals['_WRITECONTENTREQUEST']._serialized_end=599
  _globals['_WRITECONTENTREQUEST_LABELSENTRY']._serialized_start=554
  _globals['_WRITECONTENTREQUEST_LABELSENTRY']._serialized_end=599
  _globals['_WRITECONTENTRESPONSE']._serialized_start=602
  _globals['_WRITECONTENTRESPONSE']._serialized_end=745
  _globals['_CONTENT']._serialized_start=796
  _globals['_CONTENT']._serialized_end=1139
# @@protoc_insertion_point(module_scope)
