#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ctrd_images.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ctrd_images.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63trd_images.proto\x12\x1d\x63ontainerd.services.images.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xc3\x01\n\nDescriptor\x12\x12\n\nmedia_type\x18\x01 \x01(\t\x12\x0e\n\x06\x64igest\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x03\x12O\n\x0b\x61nnotations\x18\x05 \x03(\x0b\x32:.containerd.services.images.v1.Descriptor.AnnotationsEntry\x1a\x32\n\x10\x41nnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc1\x01\n\x05Image\x12\x0c\n\x04name\x18\x01 \x01(\t\x12@\n\x06labels\x18\x02 \x03(\x0b\x32\x30.containerd.services.images.v1.Image.LabelsEntry\x12\x39\n\x06target\x18\x03 \x01(\x0b\x32).containerd.services.images.v1.Descriptor\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1f\n\x0fGetImageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"G\n\x10GetImageResponse\x12\x33\n\x05image\x18\x01 \x01(\x0b\x32$.containerd.services.images.v1.Image\"I\n\x12\x43reateImageRequest\x12\x33\n\x05image\x18\x01 \x01(\x0b\x32$.containerd.services.images.v1.Image\"J\n\x13\x43reateImageResponse\x12\x33\n\x05image\x18\x01 \x01(\x0b\x32$.containerd.services.images.v1.Image\"0\n\x12\x44\x65leteImageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04sync\x18\x02 \x01(\x08\x32\xb6\x02\n\x06Images\x12\x66\n\x03Get\x12..containerd.services.images.v1.GetImageRequest\x1a/.containerd.services.images.v1.GetImageResponse\x12o\n\x06\x43reate\x12\x31.containerd.services.images.v1.CreateImageRequest\x1a\x32.containerd.services.images.v1.CreateImageResponse\x12S\n\x06\x44\x65lete\x12\x31.containerd.services.images.v1.DeleteImageRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ctrd_images_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DESCRIPTOR_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_DESCRIPTOR_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_IMAGE_LABELSENTRY']._loaded_options = None
  _globals['_IMAGE_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_DESCRIPTOR']._serialized_start=82
  _globals['_DESCRIPTOR']._serialized_end=277
  _globals['_DESCRIPTOR_ANNOTATIONSENTRY']._serialized_start=227
  _globals['_DESCRIPTOR_ANNOTATIONSENTRY']._serialized_end=277
  _globals['_IMAGE']._serialized_start=280
  _globals['_IMAGE']._serialized_end=473
  _globals['_IMAGE_LABELSENTRY']._serialized_start=428
  _globals['_IMAGE_LABELSENTRY']._serialized_end=473
  _globals['_GETIMAGEREQUEST']._serialized_start=475
  _globals['_GETIMAGEREQUEST']._serialized_end=506
  _globals['_GETIMAGERESPONSE']._serialized_start=508
  _globals['_GETIMAGERESPONSE']._serialized_end=579
  _globals['_CREATEIMAGEREQUEST']._serialized_start=581
  _globals['_CREATEIMAGEREQUEST']._serialized_end=654
  _globals['_CREATEIMAGERESPONSE']._serialized_start=656
  _globals['_CREATEIMAGERESPONSE']._serialized_end=730
  _globals['_DELETEIMAGEREQUEST']._serialized_start=732
  _globals['_DELETEIMAGEREQUEST']._serialized_end=780
  _globals['_IMAGES']._serialized_start=783
  _globals['_IMAGES']._serialized_end=1093
# @@protoc_insertion_point(module_scope)
