#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ctrd_transfer_types.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ctrd_transfer_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63trd_transfer_types.proto\x12\x19\x63ontainerd.types.transfer\"\x8c\x01\n\nImageStore\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x41\n\x06labels\x18\x02 \x03(\x0b\x32\x31.containerd.types.transfer.ImageStore.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"_\n\x0bOCIRegistry\x12\x11\n\treference\x18\x01 \x01(\t\x12=\n\x08resolver\x18\x02 \x01(\x0b\x32+.containerd.types.transfer.RegistryResolver\"\xcc\x01\n\x10RegistryResolver\x12\x13\n\x0b\x61uth_stream\x18\x01 \x01(\t\x12I\n\x07headers\x18\x02 \x03(\x0b\x32\x38.containerd.types.transfer.RegistryResolver.HeadersEntry\x12\x10\n\x08host_dir\x18\x03 \x01(\t\x12\x16\n\x0e\x64\x65\x66\x61ult_scheme\x18\x04 \x01(\t\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ctrd_transfer_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGESTORE_LABELSENTRY']._loaded_options = None
  _globals['_IMAGESTORE_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_REGISTRYRESOLVER_HEADERSENTRY']._loaded_options = None
  _globals['_REGISTRYRESOLVER_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_IMAGESTORE']._serialized_start=57
  _globals['_IMAGESTORE']._serialized_end=197
  _globals['_IMAGESTORE_LABELSENTRY']._serialized_start=152
  _globals['_IMAGESTORE_LABELSENTRY']._serialized_end=197
  _globals['_OCIREGISTRY']._serialized_start=199
  _globals['_OCIREGISTRY']._serialized_end=294
  _globals['_REGISTRYRESOLVER']._serialized_start=297
  _globals['_REGISTRYRESOLVER']._serialized_end=501
  _globals['_REGISTRYRESOLVER_HEADERSENTRY']._serialized_start=455
  _globals['_REGISTRYRESOLVER_HEADERSENTRY']._serialized_end=501
# @@protoc_insertion_point(module_scope)
