#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from zun.criapi import imaging_pb2 as imaging__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in imaging_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiffStub:
    """---------------------------------------------------------------- diff

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Diff = channel.unary_unary(
                '/zun.criapi.imaging.Diff/Diff',
                request_serializer=imaging__pb2.DiffRequest.SerializeToString,
                response_deserializer=imaging__pb2.DiffResponse.FromString,
                _registered_method=True)


class DiffServicer:
    """---------------------------------------------------------------- diff

    """

    def Diff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiffServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Diff': grpc.unary_unary_rpc_method_handler(
                    servicer.Diff,
                    request_deserializer=imaging__pb2.DiffRequest.FromString,
                    response_serializer=imaging__pb2.DiffResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zun.criapi.imaging.Diff', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zun.criapi.imaging.Diff', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Diff:
    """---------------------------------------------------------------- diff

    """

    @staticmethod
    def Diff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zun.criapi.imaging.Diff/Diff',
            imaging__pb2.DiffRequest.SerializeToString,
            imaging__pb2.DiffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ContentStub:
    """------------------------------------------------------------- content

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/zun.criapi.imaging.Content/Info',
                request_serializer=imaging__pb2.InfoRequest.SerializeToString,
                response_deserializer=imaging__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_stream(
                '/zun.criapi.imaging.Content/Read',
                request_serializer=imaging__pb2.ReadContentRequest.SerializeToString,
                response_deserializer=imaging__pb2.ReadContentResponse.FromString,
                _registered_method=True)
        self.Write = channel.stream_stream(
                '/zun.criapi.imaging.Content/Write',
                request_serializer=imaging__pb2.WriteContentRequest.SerializeToString,
                response_deserializer=imaging__pb2.WriteContentResponse.FromString,
                _registered_method=True)


class ContentServicer:
    """------------------------------------------------------------- content

    """

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=imaging__pb2.InfoRequest.FromString,
                    response_serializer=imaging__pb2.InfoResponse.SerializeToString,
            ),
            'Read': grpc.unary_stream_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=imaging__pb2.ReadContentRequest.FromString,
                    response_serializer=imaging__pb2.ReadContentResponse.SerializeToString,
            ),
            'Write': grpc.stream_stream_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=imaging__pb2.WriteContentRequest.FromString,
                    response_serializer=imaging__pb2.WriteContentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zun.criapi.imaging.Content', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zun.criapi.imaging.Content', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Content:
    """------------------------------------------------------------- content

    """

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zun.criapi.imaging.Content/Info',
            imaging__pb2.InfoRequest.SerializeToString,
            imaging__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/zun.criapi.imaging.Content/Read',
            imaging__pb2.ReadContentRequest.SerializeToString,
            imaging__pb2.ReadContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/zun.criapi.imaging.Content/Write',
            imaging__pb2.WriteContentRequest.SerializeToString,
            imaging__pb2.WriteContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ImagesStub:
    """-------------------------------------------------------------- images

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/zun.criapi.imaging.Images/Get',
                request_serializer=imaging__pb2.GetImageRequest.SerializeToString,
                response_deserializer=imaging__pb2.GetImageResponse.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/zun.criapi.imaging.Images/Create',
                request_serializer=imaging__pb2.CreateImageRequest.SerializeToString,
                response_deserializer=imaging__pb2.CreateImageResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/zun.criapi.imaging.Images/Delete',
                request_serializer=imaging__pb2.DeleteImageRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ImagesServicer:
    """-------------------------------------------------------------- images

    """

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImagesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=imaging__pb2.GetImageRequest.FromString,
                    response_serializer=imaging__pb2.GetImageResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=imaging__pb2.CreateImageRequest.FromString,
                    response_serializer=imaging__pb2.CreateImageResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=imaging__pb2.DeleteImageRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zun.criapi.imaging.Images', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zun.criapi.imaging.Images', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Images:
    """-------------------------------------------------------------- images

    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zun.criapi.imaging.Images/Get',
            imaging__pb2.GetImageRequest.SerializeToString,
            imaging__pb2.GetImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zun.criapi.imaging.Images/Create',
            imaging__pb2.CreateImageRequest.SerializeToString,
            imaging__pb2.CreateImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zun.criapi.imaging.Images/Delete',
            imaging__pb2.DeleteImageRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
