# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tasks.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tasks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x1c\x63ontainerd.services.tasks.v1\x1a\x1bgoogle/protobuf/empty.proto\"(\n\x10PauseTaskRequest\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\")\n\x11ResumeTaskRequest\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\"Q\n\x0bKillRequest\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\x0f\n\x07\x65xec_id\x18\x02 \x01(\t\x12\x0e\n\x06signal\x18\x03 \x01(\r\x12\x0b\n\x03\x61ll\x18\x04 \x01(\x08\"3\n\nGetRequest\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\x0f\n\x07\x65xec_id\x18\x02 \x01(\t\"E\n\x0bGetResponse\x12\x36\n\x07process\x18\x01 \x01(\x0b\x32%.containerd.services.tasks.v1.Process\"\xcd\x01\n\x07Process\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\r\x12<\n\x06status\x18\x04 \x01(\x0e\x32,.containerd.services.tasks.v1.Process.Status\"U\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x43REATED\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\x0b\n\x07STOPPED\x10\x03\x12\n\n\x06PAUSED\x10\x04\x12\x0b\n\x07PAUSING\x10\x05\x32\xd2\x02\n\x05Tasks\x12Z\n\x03Get\x12(.containerd.services.tasks.v1.GetRequest\x1a).containerd.services.tasks.v1.GetResponse\x12I\n\x04Kill\x12).containerd.services.tasks.v1.KillRequest\x1a\x16.google.protobuf.Empty\x12O\n\x05Pause\x12..containerd.services.tasks.v1.PauseTaskRequest\x1a\x16.google.protobuf.Empty\x12Q\n\x06Resume\x12/.containerd.services.tasks.v1.ResumeTaskRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAUSETASKREQUEST']._serialized_start=74
  _globals['_PAUSETASKREQUEST']._serialized_end=114
  _globals['_RESUMETASKREQUEST']._serialized_start=116
  _globals['_RESUMETASKREQUEST']._serialized_end=157
  _globals['_KILLREQUEST']._serialized_start=159
  _globals['_KILLREQUEST']._serialized_end=240
  _globals['_GETREQUEST']._serialized_start=242
  _globals['_GETREQUEST']._serialized_end=293
  _globals['_GETRESPONSE']._serialized_start=295
  _globals['_GETRESPONSE']._serialized_end=364
  _globals['_PROCESS']._serialized_start=367
  _globals['_PROCESS']._serialized_end=572
  _globals['_PROCESS_STATUS']._serialized_start=487
  _globals['_PROCESS_STATUS']._serialized_end=572
  _globals['_TASKS']._serialized_start=575
  _globals['_TASKS']._serialized_end=913
# @@protoc_insertion_point(module_scope)
